### ISSUE TITLE
Past applications/interviews

### ISSUE THREAD

**Issue by dfaulken** [umts/jobapps#21]
Query interface for past applications and interviews. Not sure how in-depth this needs to be. Don't feel like messing around with datatables.

**Comment by sherson** [comment]
Some things that'd be useful, all per (user inputted) date range:

* Total number of applicants (recruitment trends)
* Number of applicants, grouped by year of graduation (recruitment trends)
* Gender and ethnicity totals (hiring stats)

**Comment by dfaulken** [comment]
Talked to Don about this today. We can start with just a paginated list of reviewed applications, which will be better than nothing.

**Comment by Anbranin** [comment]
Move discussion of ethnicity/gender reporting to #100

**Comment by Anbranin** [comment]
I think the primary issue this references (being able to view past applications) is closed, since the view for past_applications is in master. Which pull request was it a part of? I am not sure.. it looks like it didn't have its own.
This issue has branched off into a couple other topics, which now have their own issues.

**Comment by werebus** [comment]
Year of graduation remains outstanding.  I opened a different issue for that.
