### ISSUE TITLE
Take down applications

### ISSUE THREAD

**Issue by dfaulken** [umts/jobapps#74]
ST requested that they be able to take down applications for when they're not hiring.

**Comment by dfaulken** [comment]
This involves adding an `active` (or similar) attribute to ApplicationTemplate and then having that control whether or not we show a link to be able to apply for that job.

**Comment by akaplo** [comment]
Does just adding it to <code>ApplicationTemplate</code> suffice?  Perhaps I'm not understanding what exactly ApplicationTemplate is, but I would think that we'd also need to add it to ApplicationDraft so that when someone is editing an application (a draft), they have a checkbox on that page for <code>Active</code> or not.  Then it'd need to be an attribute of <code>ApplicationRecord</code> too, because when a draft gets finalized, it gets turned into an <code>ApplicationRecord</code>.

Then, when we display open applications to a student, we loop through each department in <i>views/dashboard/student</i> and subsequently its <code>ApplicationRecord</code>s.  So...

**Comment by dfaulken** [comment]
Yes, you'll want to add the attribute to `ApplicationTemplate` and `ApplicationDraft`.

The student dashboard will only show students `ApplicationRecord` instances if they've already applied for a position. If not, it'll display `ApplicationTemplate` instances. What we're looking to do is add logic such that we don't show particular `ApplicationTemplate` instances if they're not `active`.

**Comment by dfaulken** [comment]
Assigning this to @Anbranin so we can take care of it over break.

**Comment by akaplo** [comment]
@dfaulken Sounds good! I've been basically off the grid since the 23rd so I couldn't have done much anyway. I'll be back on campus Wednesday afternoon.
